name: Build and Commit on Any PR

# 이 워크플로우는 모든 PR에 대해 실행됩니다
on:
  pull_request:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 모든 히스토리와 태그를 가져옵니다

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Node.js 버전 20으로 설정

      - name: Install dependencies
        run: |
          rm -rf package-lock.json
          npm install

      - name: Set up Git
        run: |
          git config --global user.name 'Hal-ang'
          git config --global user.email 'jpjgv05@gmail.com'

      - name: Build
        run: npm run build

      - name: Commit and push if changed
        run: |
          git add .
          git commit -m "chore: Automated build commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
