name: Release Workflow

on:
  push:
    branches:
      - master # 또는 main 브랜치로 설정

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 태그와 버전을 올바르게 계산하기 위해 전체 히스토리를 체크아웃

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # 원하는 Node.js 버전을 설정
          registry-url: "https://registry.npmjs.org/" # npm 배포를 위해 필요

      - name: Install dependencies
        run: npm install

      - name: Set up Git
        run: |
          git config --global user.name 'Hal-ang'
          git config --global user.email 'jpjgv05@gmail.com'

      - name: Commit Build Files
        run: |
          npm run build
          git add .
          git commit -m "chore: build for release"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Run release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Push changes
        run: |
          git checkout master
          git push origin master --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # - name: Publish to npm
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
