name: Release Workflow

on:
  push:
    branches:
      - master # 또는 main 브랜치로 설정

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 태그와 버전을 올바르게 계산하기 위해 전체 히스토리를 체크아웃

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # 원하는 Node.js 버전을 설정

      - name: Install dependencies
        run: npm install

      - name: Set up Git
        run: |
          git config --global user.name 'Hal-ang'
          git config --global user.email 'jpjgv05@gmail.com'

      - name: Run release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # GITHUB_TOKEN 대신 PERSONAL_ACCESS_TOKEN을 사용하는 경우
          # 해당 토큰은 GitHub에 미리 설정되어 있어야 합니다.

      - name: Push changes
        run: |
          git checkout master
          git push origin master --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
